// <auto-generated />
namespace AppWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class create_tbl_producto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_tbl_producto));
        
        string IMigrationMetadata.Id
        {
            get { return "202008080054528_create_tbl_producto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
